language: node_js

node_js: 
  - 7
  - 8
  - 9
  - 10

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: 7

install:
  - npm i

script:
  - npm build
  - npm test
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always