language: node_js

node_js: 
  - 8
  - 9
  - 10

branches:
  only:
    - master

install:
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run load
  - npm run build
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always